apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: epm
resources:
  - namespaces/epm-namespace.yaml
  - ldap/ldap-deployment.yaml
  - ldap/ldap-ui-deployment.yaml
  - databases/hcm-deployment.yaml
  - databases/cmdb-deployment.yaml
  - erp/erp-deployment.yaml
  - tools/adminer-deployment.yaml
  - monitoring/wazuh-indexer-deployment.yaml
  - monitoring/wazuh-manager-deployment.yaml
  - monitoring/wazuh-dashboard-deployment.yaml