apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-pvc
  namespace: epm
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epm-wazuh-indexer
  namespace: epm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epm-wazuh-indexer
  template:
    metadata:
      labels:
        app: epm-wazuh-indexer
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.7.3
        env:
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: INDEXER_USERNAME
          value: "admin"
        - name: INDEXER_PASSWORD
          value: "Epm@Index2025!"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: indexer-storage
          mountPath: /var/lib/wazuh-indexer
      volumes:
      - name: indexer-storage
        persistentVolumeClaim:
          claimName: wazuh-indexer-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: epm
spec:
  selector:
    app: epm-wazuh-indexer
  ports:
  - port: 9200
    targetPort: 9200
  type: ClusterIP